apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rental-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rental-service.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rental-service
            port:
              number: 8080
